apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-20T12:20:26Z
  name: k8s.example.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://storage.k8s.example.com/cluster.k8s.example.com
  dnsZone: "dnsZone_ID"
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: e
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  kubernetesVersion: 1.9.7
  masterInternalName: api.internal.cluster.k8s.example.com
  masterPublicName: api.cluster.k8s.example.com
  networkCIDR: 172.40.50.0/20
  networkID: "network_ID"
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.40.50.0/20
    subnets:
  - cidr: 172.40.50.0/24
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 172.40.51.0/24
    name: us-east-1d
    type: Public
    zone: us-east-1d
  - cidr: 172.40.52.0/24
    name: us-east-1e
    type: Public
    zone: us-east-1e
  topology:
    dns:
      type: Private
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-20T12:20:26Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.example.com
  name: master-us-east-1e
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1e
  role: Master
  subnets:
  - us-east-1e
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-20T12:20:27Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.example.com
  name: nodes
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 15
  rootVolumeType: gp2
  subnets:
  - us-east-1c
  - us-east-1d
